# Docker Compose configuration for ChefKnight
services:
  chefknight:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - TZ=UTC
